[project]
name = "mini-jira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sokolov-na", email = "225724418+sokolov-na@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "psycopg>=3.3.5",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
mini-jira = "mini_jira:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
