"""update users

Revision ID: b9a0a1f1b223
Revises: 7be0decbbe71
Create Date: 2026-09-22 00:21:38.378734

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9a0a1f1b223"
down_revision: str | Sequence[str] | None = "7be0decbbe71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        new_column_name="password_hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        new_column_name="password",
    )
    # ### end Alembic commands ###
